[db]
    host="106.54.31.127"
    username="root"
    password="ZoOMus123"
    schema="MulKids"
    port=3308

[memcached]
    hosts=["workdoc_memcached_1:11211"]
[log]
    level="debug"

[job]
    EndClassOccurrClassOccurrencesCron="0 */1 * * *"
    DeductUserPlanAfterClass="0 */1 * * *"