WebCacheDir="./webcache"
ClassFilePrefix="/MitKids"

[db]
    host="106.54.31.127"
    username="root"
    password="ZoOMus123"
    schema="MulKids"
    port=3308

[memcached]
    hosts=["workdoc_memcached_1:11211"]
[log]
    level="debug"

[job]
    EndClassOccurrClassOccurrencesCron="*/1 * * * *"
    DeductUserPlanAfterClass="0 */1 * * *"
[soc]
    url="https://mitkids-1300207290.cos.ap-guangzhou.myqcloud.com"
    SecretID="AKIDiDSQDkR5tDHLbet5QX5NO9eIl01mlXVy"
    SecretKey="TgdoiNwfAzazA3f18yYs0uX0C8nZ4KJ0"
