version: '3'
services:
  web01:
    depends_on:
      - db
      - memcached
    build: .
    restart: always
    volumes:
      - ./:/app/mulkids
      - ./logs:/go-docker/logs
      - ./gocache:/go/pkg/mod/cache
    ports:
      - 8080:8080
  memcached:
      restart: always
      image: 'bitnami/memcached:1'
      ports:
        - '11211:11211'
  db:
    image: mysql:5.7
    ports:
      - '3308:3306'
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ZoOMus123
      MYSQL_DATABASE: MulKids
      MYSQL_USER: root
      MYSQL_PASSWORD: ZoOMus123