package consts

const (
	FREE_TRIAL_PLAN    = 1
	THREE_MONTHS_PLAN  = 2
	SIX_MONTHS_PLAN    = 3
	NINE_MONTHS_PLAN   = 4
	TWELVE_MONTHS_PLAN = 5
	PROMOTION_PLAN     = 6
	LEAVE_PLAN         = 7

	PLAN_NOACTIVE_STATUS = 1
	PLAN_ACTIVE_STATUS   = 2
)
